on:
  - push
  - pull_request

jobs:
  lint-core-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build-core-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      match-path: "test/**/*.sol"

  simulate-core-modules:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-simulate.yaml@main"
    with:
      match-path: "test/**/*.sol"
